@URL = http://localhost:5184

GET {{URL}}/weatherforecast/
Accept: application/json

###
POST {{URL}}/api/auth/login
Accept: application/json

###
POST {{URL}}/api/auth/signup
Accept: application/json

###
GET {{URL}}/api/users/me
Accept: application/json

###
GET {{URL}}/api/pois
Accept: application/json