// <auto-generated />
using System;
using AudioTravelling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AudioTravelling.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422091436_SeedDefaultUsers")]
    partial class SeedDefaultUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AudioTravelling.Core.Entities.AccessCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QrImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccessCodes");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.AccessSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessCodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccessCodeId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("AccessSessions");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bán kính 15m, ưu tiên thấp nhất",
                            Name = "Cơ bản",
                            Price = 0m,
                            Priority = 0,
                            RadiusMeters = 15
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bán kính 30m, ưu tiên trung bình",
                            Name = "Nâng cao",
                            Price = 200000m,
                            Priority = 1,
                            RadiusMeters = 30
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bán kính 50m, ưu tiên cao nhất",
                            Name = "Chuyên nghiệp",
                            Price = 500000m,
                            Priority = 2,
                            RadiusMeters = 50
                        });
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.Poi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PackageId");

                    b.ToTable("Pois");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.PoiApprovalLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("PoiId");

                    b.ToTable("PoiApprovalLogs");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.PoiImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("PoiImages");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.PoiLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("PoiLocalizations");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Owner"
                        });
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@audiotravelling.com",
                            PasswordHash = "$2a$11$WhkWccdt9qW.O1NdwVb76uhsDhhgR0WKytBTU24Ilnk/T.cGjWEKS",
                            RoleId = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner@audiotravelling.com",
                            PasswordHash = "$2a$11$vnHVv7WjT0NxVrxuX6T4ReyB/V9TCUCKGNSp7uBuCn/U5HaJAbQha",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.AccessSession", b =>
                {
                    b.HasOne("AudioTravelling.Core.Entities.AccessCode", "AccessCode")
                        .WithMany("Sessions")
                        .HasForeignKey("AccessCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessCode");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.Poi", b =>
                {
                    b.HasOne("AudioTravelling.Core.Entities.User", "Owner")
                        .WithMany("Pois")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioTravelling.Core.Entities.Package", "Package")
                        .WithMany("Pois")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.PoiApprovalLog", b =>
                {
                    b.HasOne("AudioTravelling.Core.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioTravelling.Core.Entities.Poi", "Poi")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.PoiImage", b =>
                {
                    b.HasOne("AudioTravelling.Core.Entities.Poi", "Poi")
                        .WithMany("Images")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.PoiLocalization", b =>
                {
                    b.HasOne("AudioTravelling.Core.Entities.Poi", "Poi")
                        .WithMany("Localizations")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.User", b =>
                {
                    b.HasOne("AudioTravelling.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.AccessCode", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.Package", b =>
                {
                    b.Navigation("Pois");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.Poi", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("Images");

                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AudioTravelling.Core.Entities.User", b =>
                {
                    b.Navigation("Pois");
                });
#pragma warning restore 612, 618
        }
    }
}
